spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/adil?verifyServerCertificate=false&useSSL=false&requireSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: root
    jpa:
        hibernate.ddl-auto: create
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL57Dialect


server:
    port: 8000

#security:
#    oauth2:
#        resource:
#            token-info-uri: ${auth-server:http://localhost:8000}/oauth/token


#zuul:
#    routes:
#        auth-service:
#            path: /auth/**
#            service-id: AUTH-SERVICE
#            strip-prefix: false
#            sensitive-headers: Cookie,Set-Cookie
#
#eureka:
#    client:
#        service-url:
#            default-zone: http://localhost:8761/eureka